CREATE TABLE `DEPARTMENT` (
  `DEPTID` int(10) NOT NULL,
  `DEPTNAME` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`DEPTID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `EMPLOYEE` (
  `EMPID` int(15) NOT NULL,
  `EMPNAME` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`EMPID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
